name: universal-ir
suffix: ~  # add suffix to saved images
model: denoising
#distortion: [motion-blurry,hazy_,jpeg-compressed,low-light,noisy,raindrop,rainy,shadowed,snowy,uncompleted] # uncompleted means inpainting
#distortion: [hazy_stage] # uncompleted means inpainting
distortion: [noisy] # uncompleted means inpainting
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005
  sampling_mode: posterior # sde or posterior
  
degradation:
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4

datasets:
  test1:
   name: Test
   mode: LQGT
#   dataroot_GT: datasets/universal/deg_type/GT
#   dataroot_GT: /home/lee/PycharmProjects/stageCLIP/universal-image-restoration/datasets/universal/val/hazy_stage/GT
   dataroot_GT: /home/lee/PycharmProjects/stageCLIP/universal-image-restoration/datasets/universal/val/noisy/GT
#   dataroot_LQ: datasets/universal/deg_type/LQ
   dataroot_LQ: /home/lee/PycharmProjects/stageCLIP/universal-image-restoration/datasets/universal/val/noisy/LQ
#   dataroot_LQ: /home/lee/PycharmProjects/stageCLIP/universal-image-restoration/datasets/universal/val/noisy/noise25

#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    ch_mult: [1, 2, 4, 8]
    context_dim: 512
    use_degra_context: true
    use_image_context: true

#### path
path:
#  pretrain_model_G: pretrained/universal-ir.pth
#  pretrain_model_G: /home/lee/PycharmProjects/stageCLIP/sde/30000_G.pth
#  pretrain_model_G: /home/lee/PycharmProjects/stageCLIP/universal-ir.pth
  pretrain_model_G: /home/lee/PycharmProjects/stageCLIP/sde/411_40000_G.pth
#  daclip: pretrained/daclip_ViT-B-32.pt
#  daclip: /home/lee/PycharmProjects/stageCLIP/da-clip/src/logs/stageCLIP_ViT-B-32-2023-09_b512x1_lr2e-5_e30_test_13/checkpoints/epoch_latest.pt
#  daclip: /home/lee/PycharmProjects/stageCLIP/daclip_ViT-B-32.pt
  daclip: /home/lee/PycharmProjects/stageCLIP/stageCLIP/411_epoch_20.pt
